version: '3.8'
services:
  scraper:
    build: .
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    depends_on:
      - postgres
    environment:
      - DB_TYPE=postgres # digunakan untuk script ekspor
      - DB_HOST=postgres
      - DB_NAME=jobs_db
      - DB_USER=postgres
      - DB_PASS=postgres
    command: ["python", "main.py"]
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
